apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ajdovscina
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ajdovscina
    newTag: '87b57570a2dd04d24290478f8f5f8589cfbe7c67'
