apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: parlameter-ajdovscina
resources:
  - cronjob.yaml
images:
  - name: parlaparser-ajdovscina
    newName: rg.fr-par.scw.cloud/djnd/parlaparser-ajdovscina
    newTag: 'a8e808fe40e84b615951a269e75894428c2eb0ae'
